language: php

sudo: false

addons:
  apt:
    packages:
      - parallel

env:
  global:
    - TYPO3_DATABASE_NAME="typo3_ci"
    - TYPO3_DATABASE_HOST="127.0.0.1"
    - TYPO3_DATABASE_USERNAME="root"
    - TYPO3_DATABASE_PASSWORD=""
    - TESTING_FRAMEWORK_VERSION=^1.1

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env: TYPO3_VERSION=^7.6
    - php: 5.6
      env: TYPO3_VERSION=^7.6
    - php: 7.0
      env: TYPO3_VERSION=^7.6
    - php: 7.1
      env: TYPO3_VERSION=^7.6
    - php: 7.1
      env: TYPO3_VERSION=^8.7
    - php: 7.0
      env: TYPO3_VERSION=^8.7

before_install:
  - composer self-update
  - composer global require friendsofphp/php-cs-fixer:^1.3

install:
  - Build/Test/bootstrap.sh
script:
  - Build/Test/cibuild.sh

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.unit.clover
  - php ocular.phar code-coverage:upload --format=php-clover coverage.functional.clover
  - Build/Test/cleanup.sh

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/solr/downloads
